import { BoardSpace, GameCard, SpaceType, PropertyColor, CardDeckType } from '@umukino/shared-types';

// ============================================================
// UMUKINO BOARD — 40 Spaces, Rwanda + International Mix
// All prices in RWF
// ============================================================

export const BOARD_SPACES: BoardSpace[] = [
  // 0 — START
  {
    index: 0,
    name: 'Start',
    nameKiny: 'Tangira',
    type: SpaceType.CORNER_START,
  },

  // 1 — BROWN GROUP
  {
    index: 1,
    name: 'Nyamirambo',
    nameKiny: 'Nyamirambo',
    type: SpaceType.PROPERTY,
    color: PropertyColor.BROWN,
    price: 12000,
    rent: [400, 2000, 4000, 10000, 30000, 50000],
    housePrice: 5000,
    hotelPrice: 5000,
    mortgage: 6000,
    group: 'brown',
  },
  {
    index: 2,
    name: 'Treasure',
    nameKiny: 'Ubutunzi',
    type: SpaceType.CARD,
    cardDeck: CardDeckType.TREASURE,
  },
  {
    index: 3,
    name: 'Kimironko',
    nameKiny: 'Kimironko',
    type: SpaceType.PROPERTY,
    color: PropertyColor.BROWN,
    price: 14000,
    rent: [600, 3000, 6000, 18000, 50000, 70000],
    housePrice: 5000,
    hotelPrice: 5000,
    mortgage: 7000,
    group: 'brown',
  },
  {
    index: 4,
    name: 'Earnings Tax (10%)',
    nameKiny: 'Umusoro ku nyungu (10%)',
    type: SpaceType.TAX,
    taxPercent: 10,
  },

  // 5 — AIRPORT
  {
    index: 5,
    name: 'Kigali International Airport',
    nameKiny: 'Ikibuga cy\'indege cya Kigali',
    type: SpaceType.AIRPORT,
    price: 40000,
    rent: [5000, 10000, 20000, 40000],
    mortgage: 20000,
    group: 'airports',
  },

  // 6-9 — LIGHT BLUE
  {
    index: 6,
    name: 'Muhanga',
    nameKiny: 'Muhanga',
    type: SpaceType.PROPERTY,
    color: PropertyColor.LIGHT_BLUE,
    price: 18000,
    rent: [1000, 5000, 15000, 45000, 62500, 75000],
    housePrice: 5000,
    hotelPrice: 5000,
    mortgage: 9000,
    group: 'light_blue',
  },
  {
    index: 7,
    name: 'Surprise',
    nameKiny: 'Igitangaza',
    type: SpaceType.CARD,
    cardDeck: CardDeckType.SURPRISE,
  },
  {
    index: 8,
    name: 'Musanze',
    nameKiny: 'Musanze',
    type: SpaceType.PROPERTY,
    color: PropertyColor.LIGHT_BLUE,
    price: 18000,
    rent: [1000, 5000, 15000, 45000, 62500, 75000],
    housePrice: 5000,
    hotelPrice: 5000,
    mortgage: 9000,
    group: 'light_blue',
  },
  {
    index: 9,
    name: 'Rubavu',
    nameKiny: 'Rubavu',
    type: SpaceType.PROPERTY,
    color: PropertyColor.LIGHT_BLUE,
    price: 20000,
    rent: [1200, 6000, 18000, 50000, 70000, 90000],
    housePrice: 5000,
    hotelPrice: 5000,
    mortgage: 10000,
    group: 'light_blue',
  },

  // 10 — JAIL (visiting)
  {
    index: 10,
    name: 'Prison',
    nameKiny: 'Gereza',
    type: SpaceType.CORNER_JAIL,
  },

  // 11-14 — PINK
  {
    index: 11,
    name: 'Huye',
    nameKiny: 'Huye',
    type: SpaceType.PROPERTY,
    color: PropertyColor.PINK,
    price: 22000,
    rent: [1800, 9000, 25000, 70000, 87500, 105000],
    housePrice: 10000,
    hotelPrice: 10000,
    mortgage: 11000,
    group: 'pink',
  },
  {
    index: 12,
    name: 'WASAC (Water)',
    nameKiny: 'WASAC (Amazi)',
    type: SpaceType.UTILITY,
    price: 15000,
    mortgage: 7500,
    group: 'utilities',
  },
  {
    index: 13,
    name: 'Nyanza',
    nameKiny: 'Nyanza',
    type: SpaceType.PROPERTY,
    color: PropertyColor.PINK,
    price: 24000,
    rent: [2000, 10000, 30000, 75000, 92500, 110000],
    housePrice: 10000,
    hotelPrice: 10000,
    mortgage: 12000,
    group: 'pink',
  },
  {
    index: 14,
    name: 'Rwamagana',
    nameKiny: 'Rwamagana',
    type: SpaceType.PROPERTY,
    color: PropertyColor.PINK,
    price: 26000,
    rent: [2200, 11000, 33000, 80000, 97500, 115000],
    housePrice: 10000,
    hotelPrice: 10000,
    mortgage: 13000,
    group: 'pink',
  },

  // 15 — AIRPORT
  {
    index: 15,
    name: 'Nairobi Airport (NBO)',
    nameKiny: 'Ikibuga cy\'indege cya Nairobi',
    type: SpaceType.AIRPORT,
    price: 40000,
    rent: [5000, 10000, 20000, 40000],
    mortgage: 20000,
    group: 'airports',
  },

  // 16-19 — ORANGE
  {
    index: 16,
    name: 'Dar es Salaam',
    nameKiny: 'Dar es Salaam',
    type: SpaceType.PROPERTY,
    color: PropertyColor.ORANGE,
    price: 28000,
    rent: [2400, 12000, 36000, 85000, 102500, 120000],
    housePrice: 10000,
    hotelPrice: 10000,
    mortgage: 14000,
    group: 'orange',
  },
  {
    index: 17,
    name: 'Treasure',
    nameKiny: 'Ubutunzi',
    type: SpaceType.CARD,
    cardDeck: CardDeckType.TREASURE,
  },
  {
    index: 18,
    name: 'Kampala',
    nameKiny: 'Kampala',
    type: SpaceType.PROPERTY,
    color: PropertyColor.ORANGE,
    price: 28000,
    rent: [2400, 12000, 36000, 85000, 102500, 120000],
    housePrice: 10000,
    hotelPrice: 10000,
    mortgage: 14000,
    group: 'orange',
  },
  {
    index: 19,
    name: 'Addis Ababa',
    nameKiny: 'Adisi Abeba',
    type: SpaceType.PROPERTY,
    color: PropertyColor.ORANGE,
    price: 30000,
    rent: [2800, 14000, 40000, 90000, 110000, 130000],
    housePrice: 10000,
    hotelPrice: 10000,
    mortgage: 15000,
    group: 'orange',
  },

  // 20 — VACATION (Free Parking)
  {
    index: 20,
    name: 'Vacation',
    nameKiny: 'Ikiruhuko',
    type: SpaceType.CORNER_VACATION,
  },

  // 21-24 — RED
  {
    index: 21,
    name: 'Johannesburg',
    nameKiny: 'Johannesburg',
    type: SpaceType.PROPERTY,
    color: PropertyColor.RED,
    price: 32000,
    rent: [3000, 15000, 45000, 95000, 115000, 140000],
    housePrice: 15000,
    hotelPrice: 15000,
    mortgage: 16000,
    group: 'red',
  },
  {
    index: 22,
    name: 'Surprise',
    nameKiny: 'Igitangaza',
    type: SpaceType.CARD,
    cardDeck: CardDeckType.SURPRISE,
  },
  {
    index: 23,
    name: 'Lagos',
    nameKiny: 'Lagos',
    type: SpaceType.PROPERTY,
    color: PropertyColor.RED,
    price: 34000,
    rent: [3200, 16000, 48000, 100000, 120000, 150000],
    housePrice: 15000,
    hotelPrice: 15000,
    mortgage: 17000,
    group: 'red',
  },
  {
    index: 24,
    name: 'Cairo',
    nameKiny: 'Kayiro',
    type: SpaceType.PROPERTY,
    color: PropertyColor.RED,
    price: 36000,
    rent: [3600, 18000, 50000, 110000, 130000, 160000],
    housePrice: 15000,
    hotelPrice: 15000,
    mortgage: 18000,
    group: 'red',
  },

  // 25 — AIRPORT
  {
    index: 25,
    name: 'Dubai Airport (DXB)',
    nameKiny: 'Ikibuga cy\'indege cya Dubai',
    type: SpaceType.AIRPORT,
    price: 40000,
    rent: [5000, 10000, 20000, 40000],
    mortgage: 20000,
    group: 'airports',
  },

  // 26-29 — YELLOW
  {
    index: 26,
    name: 'Istanbul',
    nameKiny: 'Istanbul',
    type: SpaceType.PROPERTY,
    color: PropertyColor.YELLOW,
    price: 38000,
    rent: [3800, 19000, 55000, 120000, 145000, 170000],
    housePrice: 15000,
    hotelPrice: 15000,
    mortgage: 19000,
    group: 'yellow',
  },
  {
    index: 27,
    name: 'Amsterdam',
    nameKiny: 'Amsterdam',
    type: SpaceType.PROPERTY,
    color: PropertyColor.YELLOW,
    price: 38000,
    rent: [3800, 19000, 55000, 120000, 145000, 170000],
    housePrice: 15000,
    hotelPrice: 15000,
    mortgage: 19000,
    group: 'yellow',
  },
  {
    index: 28,
    name: 'REG (Electricity)',
    nameKiny: 'REG (Amashanyarazi)',
    type: SpaceType.UTILITY,
    price: 15000,
    mortgage: 7500,
    group: 'utilities',
  },
  {
    index: 29,
    name: 'Paris',
    nameKiny: 'Pari',
    type: SpaceType.PROPERTY,
    color: PropertyColor.YELLOW,
    price: 40000,
    rent: [4000, 20000, 60000, 130000, 155000, 180000],
    housePrice: 15000,
    hotelPrice: 15000,
    mortgage: 20000,
    group: 'yellow',
  },

  // 30 — GO TO JAIL
  {
    index: 30,
    name: 'Go to Prison',
    nameKiny: 'Jya mu Gereza',
    type: SpaceType.CORNER_GO_TO_JAIL,
  },

  // 31-34 — GREEN
  {
    index: 31,
    name: 'London',
    nameKiny: 'Londere',
    type: SpaceType.PROPERTY,
    color: PropertyColor.GREEN,
    price: 45000,
    rent: [5000, 22000, 66000, 160000, 180000, 200000],
    housePrice: 20000,
    hotelPrice: 20000,
    mortgage: 22500,
    group: 'green',
  },
  {
    index: 32,
    name: 'Berlin',
    nameKiny: 'Berlin',
    type: SpaceType.PROPERTY,
    color: PropertyColor.GREEN,
    price: 45000,
    rent: [5000, 22000, 66000, 160000, 180000, 200000],
    housePrice: 20000,
    hotelPrice: 20000,
    mortgage: 22500,
    group: 'green',
  },
  {
    index: 33,
    name: 'Treasure',
    nameKiny: 'Ubutunzi',
    type: SpaceType.CARD,
    cardDeck: CardDeckType.TREASURE,
  },
  {
    index: 34,
    name: 'New York',
    nameKiny: 'New York',
    type: SpaceType.PROPERTY,
    color: PropertyColor.GREEN,
    price: 50000,
    rent: [6000, 25000, 70000, 175000, 195000, 220000],
    housePrice: 20000,
    hotelPrice: 20000,
    mortgage: 25000,
    group: 'green',
  },

  // 35 — AIRPORT
  {
    index: 35,
    name: 'JFK Airport (New York)',
    nameKiny: 'Ikibuga cy\'indege cya JFK',
    type: SpaceType.AIRPORT,
    price: 40000,
    rent: [5000, 10000, 20000, 40000],
    mortgage: 20000,
    group: 'airports',
  },

  // 36 — TAX
  {
    index: 36,
    name: 'Premium Tax',
    nameKiny: 'Umusoro w\'agaciro',
    type: SpaceType.TAX,
    taxAmount: 7500,
  },

  // 37-39 — DARK BLUE
  {
    index: 37,
    name: 'Tokyo',
    nameKiny: 'Tokyo',
    type: SpaceType.PROPERTY,
    color: PropertyColor.DARK_BLUE,
    price: 55000,
    rent: [8500, 28000, 80000, 200000, 220000, 250000],
    housePrice: 20000,
    hotelPrice: 20000,
    mortgage: 27500,
    group: 'dark_blue',
  },
  {
    index: 38,
    name: 'Surprise',
    nameKiny: 'Igitangaza',
    type: SpaceType.CARD,
    cardDeck: CardDeckType.SURPRISE,
  },
  {
    index: 39,
    name: 'Kigali CBD',
    nameKiny: 'Ikigo cy\'Ubucuruzi cya Kigali',
    type: SpaceType.PROPERTY,
    color: PropertyColor.DARK_BLUE,
    price: 70000,
    rent: [10000, 35000, 100000, 300000, 450000, 500000],
    housePrice: 20000,
    hotelPrice: 20000,
    mortgage: 35000,
    group: 'dark_blue',
  },
];

// ============================================================
// SURPRISE DECK (16 cards) — Rwanda flavor
// ============================================================

export const SURPRISE_CARDS: GameCard[] = [
  {
    id: 'S01',
    deck: CardDeckType.SURPRISE,
    text: 'Advance to Start. Collect 20,000 RWF as you pass.',
    textKiny: 'Garuka ku ntangiriro. Fata amafaranga 20,000 RWF ugeze.',
    action: 'GO_TO_START',
    amount: 20000,
  },
  {
    id: 'S02',
    deck: CardDeckType.SURPRISE,
    text: 'MTN MoMo scammer got you! Pay 8,000 RWF.',
    textKiny: 'Urimbuye wa MTN MoMo yakurimbuje! Tanga 8,000 RWF.',
    action: 'LOSE',
    amount: 8000,
  },
  {
    id: 'S03',
    deck: CardDeckType.SURPRISE,
    text: 'Your boda boda broke down on Kigali roads. Pay 5,000 RWF.',
    textKiny: 'Motos yawe yarananiwe mu nzira za Kigali. Tanga 5,000 RWF.',
    action: 'LOSE',
    amount: 5000,
  },
  {
    id: 'S04',
    deck: CardDeckType.SURPRISE,
    text: 'Bank of Kigali credited interest to your account. Collect 12,000 RWF.',
    textKiny: 'Banki y\'u Rwanda yaguheye inyungu. Fata 12,000 RWF.',
    action: 'GAIN',
    amount: 12000,
  },
  {
    id: 'S05',
    deck: CardDeckType.SURPRISE,
    text: 'Go directly to Prison. Do not pass Start. Do not collect 20,000 RWF.',
    textKiny: 'Jya mu Gereza ako kanya. Ntuzanyure ku ntangiriro.',
    action: 'GO_TO_JAIL',
  },
  {
    id: 'S06',
    deck: CardDeckType.SURPRISE,
    text: 'RURA fined your business for non-compliance. Pay 10,000 RWF.',
    textKiny: 'RURA yahanye ubucuruzi bwawe. Tanga 10,000 RWF.',
    action: 'LOSE',
    amount: 10000,
  },
  {
    id: 'S07',
    deck: CardDeckType.SURPRISE,
    text: 'You won the Umuganura festival raffle! Collect 15,000 RWF.',
    textKiny: 'Wanye tombola y\'Umuganura! Fata 15,000 RWF.',
    action: 'GAIN',
    amount: 15000,
  },
  {
    id: 'S08',
    deck: CardDeckType.SURPRISE,
    text: 'Get out of Prison free. Keep this card until needed.',
    textKiny: 'Sohoka mu Gereza ubuntu. Bika iyi karita kugeza ubwo uzayikeneye.',
    action: 'GET_OUT_OF_JAIL_FREE',
    jailFree: true,
  },
  {
    id: 'S09',
    deck: CardDeckType.SURPRISE,
    text: 'Umuganda day — everyone must contribute. Pay 3,000 RWF per player.',
    textKiny: 'Umuganda — buri wese agomba gufatanya. Tanga 3,000 RWF ku mukinnyi.',
    action: 'PAY_TO_PLAYERS',
    amount: 3000,
    perPlayer: true,
  },
  {
    id: 'S10',
    deck: CardDeckType.SURPRISE,
    text: 'Your property renovation loan approved! Collect 20,000 RWF.',
    textKiny: 'Inguzanyo y\'inzu yawe yemejwe! Fata 20,000 RWF.',
    action: 'GAIN',
    amount: 20000,
  },
  {
    id: 'S11',
    deck: CardDeckType.SURPRISE,
    text: 'Advance to Kigali International Airport.',
    textKiny: 'Jya ku Kibuga cy\'Indege cya Kigali.',
    action: 'MOVE_TO',
    moveTo: 5,
  },
  {
    id: 'S12',
    deck: CardDeckType.SURPRISE,
    text: 'RDB inspection passed — your business gets a grant! Collect 10,000 RWF.',
    textKiny: 'Igenzura rya RDB ryakunze — ubucuruzi bwawe buhawe inkunga! Fata 10,000 RWF.',
    action: 'GAIN',
    amount: 10000,
  },
  {
    id: 'S13',
    deck: CardDeckType.SURPRISE,
    text: 'Phone died, lost all your contacts. Skip your next turn.',
    textKiny: 'Telefone yawe yapfuye, wabuze za numero. Tangira ipindi ry\'undi.',
    action: 'SKIP_TURN',
  },
  {
    id: 'S14',
    deck: CardDeckType.SURPRISE,
    text: 'Move back 3 spaces.',
    textKiny: 'Subira inyuma intera 3.',
    action: 'MOVE_BY',
    moveBy: -3,
  },
  {
    id: 'S15',
    deck: CardDeckType.SURPRISE,
    text: 'Your friends collected ikimina for you! Collect 5,000 RWF from each player.',
    textKiny: 'Inshuti zawe zakuganiriye ikimina! Fata 5,000 RWF ku mukinnyi wese.',
    action: 'COLLECT_FROM_PLAYERS',
    amount: 5000,
    perPlayer: true,
  },
  {
    id: 'S16',
    deck: CardDeckType.SURPRISE,
    text: 'Street repairs assessment: pay 4,000 RWF per house, 11,500 RWF per hotel.',
    textKiny: 'Gusana inzira: tanga 4,000 RWF ku nzu, 11,500 RWF ku hotel.',
    action: 'STREET_REPAIRS',
    streetRepairs: true,
    houseCost: 4000,
    hotelCost: 11500,
  },
];

// ============================================================
// TREASURE DECK (16 cards) — Rwanda flavor
// ============================================================

export const TREASURE_CARDS: GameCard[] = [
  {
    id: 'T01',
    deck: CardDeckType.TREASURE,
    text: 'Bank error in your favor! Collect 20,000 RWF.',
    textKiny: 'Ikosa rya banki rirakugirira neza! Fata 20,000 RWF.',
    action: 'GAIN',
    amount: 20000,
  },
  {
    id: 'T02',
    deck: CardDeckType.TREASURE,
    text: 'Medical bill arrives. Pay 10,000 RWF.',
    textKiny: 'Fagitire y\'ivuriro igeze. Tanga 10,000 RWF.',
    action: 'LOSE',
    amount: 10000,
  },
  {
    id: 'T03',
    deck: CardDeckType.TREASURE,
    text: 'You received a government stimulus. Collect 20,000 RWF.',
    textKiny: 'Wahawe inkunga ya leta. Fata 20,000 RWF.',
    action: 'GAIN',
    amount: 20000,
  },
  {
    id: 'T04',
    deck: CardDeckType.TREASURE,
    text: 'MUTUELLE DE SANTE refunded your hospital fees. Collect 7,500 RWF.',
    textKiny: 'Mutuelle de Santé yagusubije amafaranga y\'ibitaro. Fata 7,500 RWF.',
    action: 'GAIN',
    amount: 7500,
  },
  {
    id: 'T05',
    deck: CardDeckType.TREASURE,
    text: 'Go directly to Prison. Do not pass Start.',
    textKiny: 'Jya mu Gereza ako kanya. Ntuzanyure ku ntangiriro.',
    action: 'GO_TO_JAIL',
  },
  {
    id: 'T06',
    deck: CardDeckType.TREASURE,
    text: 'Your agaseke (basket) sold at the craft market. Collect 5,000 RWF.',
    textKiny: 'Agaseke kawe kakagurishijwe. Fata 5,000 RWF.',
    action: 'GAIN',
    amount: 5000,
  },
  {
    id: 'T07',
    deck: CardDeckType.TREASURE,
    text: 'Property tax bill due. Pay 8,000 RWF.',
    textKiny: 'Fagitire y\'umusoro w\'imitungo igeze. Tanga 8,000 RWF.',
    action: 'LOSE',
    amount: 8000,
  },
  {
    id: 'T08',
    deck: CardDeckType.TREASURE,
    text: 'Get out of Prison free. Keep this card until needed.',
    textKiny: 'Sohoka mu Gereza ubuntu. Bika iyi karita.',
    action: 'GET_OUT_OF_JAIL_FREE',
    jailFree: true,
  },
  {
    id: 'T09',
    deck: CardDeckType.TREASURE,
    text: 'Advance to Start. Collect 20,000 RWF.',
    textKiny: 'Garuka ku ntangiriro. Fata 20,000 RWF.',
    action: 'GO_TO_START',
    amount: 20000,
  },
  {
    id: 'T10',
    deck: CardDeckType.TREASURE,
    text: 'It\'s your birthday! Collect 2,000 RWF from each player.',
    textKiny: 'Ni isabukuru yawe! Fata 2,000 RWF ku mukinnyi wese.',
    action: 'COLLECT_FROM_PLAYERS',
    amount: 2000,
    perPlayer: true,
  },
  {
    id: 'T11',
    deck: CardDeckType.TREASURE,
    text: 'Your startup won a Hanga Roundtable prize! Collect 25,000 RWF.',
    textKiny: 'Sitati yawe yanye igihembo cya Hanga! Fata 25,000 RWF.',
    action: 'GAIN',
    amount: 25000,
  },
  {
    id: 'T12',
    deck: CardDeckType.TREASURE,
    text: 'Life insurance matures. Collect 10,000 RWF.',
    textKiny: 'Ubwishingizi bw\'ubuzima burageze. Fata 10,000 RWF.',
    action: 'GAIN',
    amount: 10000,
  },
  {
    id: 'T13',
    deck: CardDeckType.TREASURE,
    text: 'Street repairs: pay 2,500 RWF per house, 10,000 RWF per hotel.',
    textKiny: 'Gusana inzira: tanga 2,500 RWF ku nzu, 10,000 RWF ku hotel.',
    action: 'STREET_REPAIRS',
    streetRepairs: true,
    houseCost: 2500,
    hotelCost: 10000,
  },
  {
    id: 'T14',
    deck: CardDeckType.TREASURE,
    text: 'Hospital and school fees due. Pay 15,000 RWF.',
    textKiny: 'Amafaranga y\'ibitaro n\'amashuri. Tanga 15,000 RWF.',
    action: 'LOSE',
    amount: 15000,
  },
  {
    id: 'T15',
    deck: CardDeckType.TREASURE,
    text: 'You won second prize in a beauty contest! Collect 10,000 RWF.',
    textKiny: 'Wanye igihembo cya kabiri mu gikorwa cy\'ubwiza! Fata 10,000 RWF.',
    action: 'GAIN',
    amount: 10000,
  },
  {
    id: 'T16',
    deck: CardDeckType.TREASURE,
    text: 'Tax refund received. Collect 15,000 RWF.',
    textKiny: 'Wasubijwe umusoro. Fata 15,000 RWF.',
    action: 'GAIN',
    amount: 15000,
  },
];

// ============================================================
// BOARD CONFIG
// ============================================================

export const BOARD_CONFIG = {
  totalSpaces: 40,
  startingBalance: 150000,     // RWF
  passStartBonus: 20000,       // RWF
  jailFine: 5000,              // RWF
  jailPosition: 10,
  goToJailPosition: 30,
  maxJailTurns: 3,
  maxHouses: 4,
  airportRents: [5000, 10000, 20000, 40000], // 1,2,3,4 airports owned
  utilityMultipliers: [4, 10], // 1 utility = 4× dice, 2 utilities = 10× dice
  auctionTimeSeconds: 30,
  turnTimeSeconds: 60,
  tradeExpirySeconds: 120,
} as const;

// Group counts for rent calculation
export const COLOR_GROUP_SIZES: Record<string, number> = {
  brown: 2,
  light_blue: 3,
  pink: 3,
  orange: 3,
  red: 3,
  yellow: 3,
  green: 3,
  dark_blue: 2,
  airports: 4,
  utilities: 2,
};
